apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  namespace: 
spec:
  rules:
    - host: ydomain.com
      http:
        paths:
          - path: /docs
            backend:
              service:
                name: api-service   
                port: 8000
                 
