name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    # Allows you to run this workflows manually from the Actions tab
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
permissions:
  contents: read          # Read permission for repository contents
  issues: write           # Required to create and manage issues for approval
  pull-requests: write    # Required if approvals are tied to PRs
  actions: write          # Allows running actions and writing to workflows

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    # Manual approval step (restricted to specific users)
    - uses: trstringer/manual-approval@v1
      if: github.ref == 'refs/heads/main'
      with:
        secret: ${{ github.TOKEN }}
        approvers: Prateek-9814
        minimum-approvals: 1
        issue-title: "Deploying v1.3.5 to prod from staging"
        issue-body: "Please approve or deny the deployment of version v1.3.5."
        exclude-workflow-initiator-as-approver: false
        additional-approved-words: ''
        additional-denied-words: ''
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

